# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: pmsContRegConnection
- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'package -Dmaven.test.skip=true'
    options: '-Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true'
- task: Docker@2
  displayName: Push
  inputs:
    command: push
    repository: manuelrojas19/pms-project-service
    containerRegistry: pmsContRegConnection
    tags: latest

